### PR TITLE
Fixed bug where cumulative GPA calculation would double count semester

### LINKED ISSUE #159: Last semester GPA and cumulative GPA features not working
It seems that SAS has disabled the grade history tab on powerschool, they also appear to have changed something about the page itself(which is still accessible by directly going to the https://powerschool.sas.edu.sg/guardian/termgrades.html url) causing the extension to be unable to calculate cumulative GPA and last semester GPA.

### PR DESCRIPTION
**Pull request by insertcustomname**
Closes #159 

Fixed bug where cumulative GPA calculation would double count semester if grade history was updated early. 

Also added null check to calculating second semester GPA and cumulative GPA.

### CODE REVIEW

**Comment by gary-kim** [comment]
BTW, you can just type `closes #159` in your description instead of linking issues through the options. That's just more portable if the project every moves off GitHub.

**Comment by insertcustomname** [comment]
closes #159

File: src/js/saspowerschoolff.js [hunk 1]
```diff
@@ -142,19 +147,27 @@ function main_page () {
...
                     }
                     $("table[border='0'][cellpadding='3'][cellspacing='1'][width='100%']").prepend(`<tr><td align="center">Last Semester GPA (S1): ${calculate_gpa(courses_first_semester)}</td></tr>`);
                 }
             });
     }
     $("table[border='0'][cellpadding='3'][cellspacing='1'][width='100%']").prepend(`<td style="background-color: white;" align="center"><button id="calculateCumulative">Calculate Cumulative GPA</button></td>`);
     // passing courses in to possibly include current semester GPA if term has not finished yet.
+    if (second_semester) {
+        current_semester = 2;
+    }
```
Comment (gary-kim) [inline src/js/saspowerschoolff.js:168]: Any reason you can't just keep using the boolean and do something like `second_semester ? 2 : 1` if you need it in numerical form?

File: src/js/saspowerschoolff.js [hunk 2]
```diff
@@ -227,35 +242,50 @@ function calculate_cumulative_gpa (current_courses) {
...
+                                    }
                                     // Creates course object with each course from grade history page
-                                    const course = new Course($prev_course.getElementsByTagName("td")[0].textContent.trim(), "",
-                                        $prev_course.getElementsByTagName("td")[1].textContent.trim(), 0, "");
-
-                                    courses.push(course);
                                 }
                             }
+                            if (i === 0) {
+                                current_term_grades.push(courses);
```
[the remark this answers is not in the document]
Comment (insertcustomname) [reply src/js/saspowerschoolff.js:263]: Yeah, once for first semester courses and once for second if it exists in the same term.

File: src/js/saspowerschoolff.js [hunk 3]
```diff
@@ -227,35 +239,50 @@ function calculate_cumulative_gpa (current_courses) {
...
-            }
-            if (include_current_semester) {
-                all_courses.push(current_courses);
-            }
-            const cumulative_gpa = Promise.all(fetches).then(function () {
+                // Handles edge case where grade history page is updated before semester end
+                if (current_term_history === current_term && include_current_semester && current_term_grades.length === 2 && current_semester) {
+                    include_current_semester = false;
+                } else if (current_term_history === current_term && include_current_semester && current_term_grades.length === 1 && current_semester === false) {
+                    include_current_semester = false;
```
Comment (gary-kim) [inline src/js/saspowerschoolff.js:280]: You could combine these as `if ((current_term_history === current_term && include_current_semester) && ((current_term_grades.length === 1 && current_semester === false) || (current_term_grades.length === 2 && current_semester)))`, obviously with some lines breaks because that's kind of unreadable.

**Comment by insertcustomname** [comment]
could you push a new version soon so that the bug is resolved for users?

**Comment by gary-kim** [comment]
The [version](https://github.com/gary-kim/saspes/milestone/10?closed=1) with the feature has not been released yet but yes, let's get this out asap, it's behind schedule anyways.

Before that though, I was testing the feature for myself and I think I've run into an issue. With the `calculate_gpa` function, it specifically excludes courses that have a grade that it cannot parse. The cumulative gpa function is not considering that so it is adding courses pass/fail courses and courses without a grade. I'm making a fix for that at the moment.

Also, I'm worried about people potentially using this number to submit to colleges. I want to put some very noticeable message saying to go to Cialfo for you official cumulative GPA to submit to colleges. Any idea how we could do that?

**Comment by insertcustomname** [comment]
We could have a popup when you press the calculate cumulative button with a disclaimer.

**Comment by insertcustomname** [comment]
Maybe only have it popup the first time they press it though.

**Comment by gary-kim** [comment]
> Maybe only have it popup the first time they press it though, and have it note that the estimation includes their current GPA which might not be counted yet on Cialfo.

How about we put that in a tooltip that people get when they hover over the calculate button or the calculated value?

**Comment by insertcustomname** [comment]
Yeah that could work, but wouldn't that need Vue or something else to do?

**Comment by gary-kim** [comment]
> Yeah that could work, but wouldn't that need Vue or something else to do?

I'll migrate your code over to work with Vue. Shouldn't be hard.
